Significant-Gravitas/Auto-GPT-Plugins

src/autogpt_plugins/twitter/README.md

Added a missing ` and updated title

Updated twitter README.md

---

README.md

Added third party plugins sections to readme. I think we should also collect third party repositories here to avoid double work.

Added third party plugins sections to readme.

---

.github/CODEOWNERS
README.md

Require a user for each plugin to be the point of contact

Add Codeowners Tools

---

README.md

Use the new plugin dependency mechanism to install the requirements without having to unzip things by hand

Use new plugin dependency mechanism

---

src/autogpt_plugins/scenex/README.md

- add a demo image
- change scenex to its fullname scenexplain

chore: improve readability of scenexplain plugin readability

---

README.md

This plugin add new command: `tidb_sql_executor`, which directly exectue sql in your TiDB Serverless database
Example:
https://user-images.githubusercontent.com/10102304/234223704-1ca4d2da-9848-44fb-9498-6be50f39a574.mp4

Add tidb serverless plugin

---

README.md

added a link to the mastodon plugin to third party plugins

Update README.md - add link to mastodon plugin

---

.github/CODEOWNERS
.gitignore
README.md
src/autogpt_plugins/wikipedia_search/README.md
src/autogpt_plugins/wikipedia_search/__init__.py
src/autogpt_plugins/wikipedia_search/wikipedia_search.py

Added capability to interact directly with Wikipedia search.
PS I also updated `.gitignore` to exclude `.idea` files.

Wikipedia search plugin

---

src/autogpt_plugins/email/email_plugin/email_plugin.py
src/autogpt_plugins/email/email_plugin/test_email_plugin.py

GMail users are using a special imap folder structure, this now adjusts for this case.
Search with whitespace needs to be enclosed in quotes.

Fix for GMail users and search with whitespace

---

.github/CODEOWNERS
README.md
requirements.txt
src/autogpt_plugins/news_search/README.md
src/autogpt_plugins/news_search/__init__.py
src/autogpt_plugins/news_search/news_search.py
src/autogpt_plugins/news_search/test_auto_gpt_news_search.py

Adds News API Integration into AutoGPT

Add first version of NewsAPI plugin

---

README.md

Seamless Integration: The AutoGPT Alpaca Trading Plugin effortlessly integrates with the Alpaca API, enabling users to harness the power of GPT-4 for advanced trading strategies and decision-making processes.
Dynamic Market Analysis: With real-time market data access, the plugin allows GPT-4 to analyze trends, prices, and fundamentals, enabling the AI to make informed decisions and generate contextually relevant trade recommendations.
The AutoGPT iMessage Plugin allows AutoGPT to send, get, and analyze text messages.
- The plugin does not require AutoGPT to run on a Mac and instead makes requests to a user-hosted imessage server
- This allows AutoGPT to run on Linux/Mac/Windows and still utilize the plugin

Added AutoGPT Alpaca-Trading Plugin and AutoGPT iMessage Plugin 

---

README.md

added the weather plugin to the third party list

Add weather plugin to 3rd party list

---

README.md

Add Spoonacular plugin
https://github.com/minfenglu/Auto-GPT-Spoonacular-Plugin

add spoonacular plugin

---

README.md

A plugin to enable Auto-GPT to click elements, input text, and scroll, bringing much more functionality and use cases into Auto-GPT.

Add Web Interaction Plugin

---

README.md

put the lists into alphabetical orders for easier comprehension

Update README.md, sort plugin lists in alphabetical order

---

src/autogpt_plugins/astro/astronauts.py

Add comments to the source code for the Astro plugin so it can more easily be understood.

Add comments to the source code for the Astro plugin

---

src/autogpt_plugins/planner/README.md
src/autogpt_plugins/planner/__init__.py
src/autogpt_plugins/planner/planner.py

Planner Plugin 

---

src/autogpt_plugins/telegram/README.md
src/autogpt_plugins/telegram/__init__.py
src/autogpt_plugins/telegram/telegram_chat.py

I added a few changes to the telegram plugin, cleaning it up a bit and also added a helper to get the chat id,
as many people don't know how to use postman or curl to retrieve it.

improvements for telegram plugin

---

README.md

Updating plugin documentation to match the current stable version.

Update README to match 0.4.2

---

src/autogpt_plugins/planner/planner.py

plugin was using the wrong path for the workspace

fixed workspace directory

---

README.md

I've added my plugin into the list. 
Auto-GPT Website-Carbon-Footprint Plugin: Take advantage of the Website Carbon Footprint API with Auto-GPT. 
Glad to participate in this project.

Update README.md to add the Website-Carbon-Footprint Plugin.

---

README.md

Added AutoGPTReddit to third party plugins

Added AutoGPTReddit to third party plugins

---

README.md

Mindware: The App Store for AutoGPT plugins

Update README.md to add the Mindware Plugin.

---

src/autogpt_plugins/astro/README.md
src/autogpt_plugins/astro/__init__.py
src/autogpt_plugins/astro/astronauts.py
src/autogpt_plugins/astro/test_astro_plugin.py

This change allows an AutoGPT agent to access the coordinates of the International Space Station.

Add an ISS position tracker to the Astro plugin
